import Head from 'next/head'
import {MainBlock} from "../components/MainBlock/MainBlock";
import {Footer} from "../components/Footer/Footer";
import React from "react";
import {Provider} from "react-redux";
import store from '../store';
import {Header} from "../components/Header/Header";

export default function Home() {
  return (
    <>
        <Provider store={store}>
            <Header/>
            <MainBlock/>
            <Footer/>
        </Provider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
    </>
  )
}
